version: '2'
services:
    fastdfssracker:
        restart: always
        image: evan1120/fastdfs_tracker
        hostname: fastdfs-tracker
        volumes:
        - ./config/:/etc/fdfs
        - /data/fastdfs:/data/fastdfs
        ports:
        - 22122:22122
        container_name: fastdfs_tracker
        network_mode: "host"
    fastdfsstorage:
        restart: always
        image: evan1120/fastdfs_storage
        hostname: fastdfs-storage
        volumes:
        - ./config/:/etc/fdfs
        - /data/fastdfs:/data/fastdfs
        ports:
        - 23000:23000
        - 8899:8899
        container_name: fastdfs-storage
        network_mode: "host"

